### ISSUE TITLE
No module named 'emoji'

### ISSUE THREAD

**Issue by LinusGeffarth** [kununu/slackdump2html#10]
Hi there, thanks for making this library 🙏

I followed the instructions and exported the channels (txt), emoji (folder) and users (txt).
When I run `python3 slackdump2html.py [channel id].json`, I get this error:

> No module named 'emoji'

What do I need to do?

Thanks!

![2023-10-27 15 20 23](https://github.com/kununu/slackdump2html/assets/9455439/a1e86ee0-f354-4e73-9d94-53a2f4783ff2)

**Comment by DerDodo** [comment]
Hi @LinusGeffarth, please make sure to follow the setup guide in the Readme file. Especially the part about python dependencies. The Pipfiles refers to the packages that need to be installed :)

**Comment by LinusGeffarth** [comment]
I did follow the steps and installed the dependencies multiple times. Do you see that one is missing?

**Comment by DerDodo** [comment]
@LinusGeffarth "No module named 'emoji'" refers to the emoji package which is mentioned in the Pipfile. Try to run:
`pipenv install
pipenv shell
python3 slackdump2html.py [channel id].json`
This is the way we typically run it.
